export const CONTEXT_TYPEs = {
  //AUTH
  SET_USER: "SET_USER",
  REMOVE_USER: "REMOVE_USER",

  //IMAGE

  //UI

  REFRESH_UI: "REFRESH_UI",
  PROFILE_FORM: "PROFILE_FORM",
  MANAGER_FORM: "MANAGER_FORM",
  EMPLOYEE_FORM: "EMPLOYEE_FORM",
  PET_FORM: "PET_FORM",
  PRODUCT_FORM: "PRODUCT_FORM",
  CUSTOMER_FORM: "CUSTOMER_FORM",
  VETERINARY_FORM: "VETERINARY_FORM",
  CLINIC_FORM: "CLINIC_FORM",

  //UTIL
  REFRESH_UTIL: "REFRESH_UTIL",
  OPERATION: "OPERATION",

  //OPERATION
  MAKE_EMPLOYEE: "MAKE_EMPLOYEE",
  MAKE_MANAGER: "MAKE_MANAGER",

  MAKE_HIGH_MANAGER: "MAKE_HIGH_MANAGER",
  DELETE_MANAGER: "DELETE_MANAGER",
  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  DELETE_PET: "DELETE_PET",
  DELETE_CUSTOMER: "DELETE_CUSTOMER",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  DELETE_VETERINARY: "DELETE_VETERINARY",
  ADOPT: "ADOPT",
  BUY: "BUY",

  //IMAGE

  PET_IMAGE: "PET_IMAGE",
  PRODUCT_IMAGE: "PRODUCT_IMAGE",
};
