export const CONTEXT_TYPEs = {
  //AUTH
  SET_USER: "SET_USER",
  REMOVE_USER: "REMOVE_USER",

  //IMAGE

  //UI

  REFRESH_UI: "REFRESH_UI",
  PROFILE_FORM: "PROFILE_FORM",
  EMPLOYEE_FORM: "EMPLOYEE_FORM",
  DEPARTMENT_FORM: "DEPARTMENT_FORM",

  MACHINE_FORM: "MACHINE_FORM",
  OIL_FORM: "OIL_FORM",
  STORAGE_FORM: "STORAGE_FORM",
  ORDER_FORM: "ORDER_FORM",
  DELIVERY_FORM: "DELIVERY_FORM",

  //UTIL
  REFRESH_UTIL: "REFRESH_UTIL",
  OPERATION: "OPERATION",

  //OPERATION
  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  DELETE_DEPARTMENT: "DELETE_DEPARTMENT",
  DELETE_MACHINE: "DELETE_MACHINE",
  DELETE_OIL: "DELETE_OIL",
  DELETE_STORAGE: "DELETE_STORAGE",
  DELETE_ORDER: "DELETE_ORDER",
  DELETE_DELIVERY: "DELETE_DELIVERY",
};
